### ISSUE TITLE
pip install failed

### ISSUE THREAD

**Issue by yinzuojie** [hermanschaaf/mafan#18] opened 2016-11-10 08:06 UTC
D:\prog\comp.lang.python\代码>pip3 install --trusted-host mirrors.zte.com.cn  -i http://mirrors.zte.com.cn/pypi/simple mafan
Collecting mafan
  Downloading http://mirrors.zte.com.cn/pypi/packages/b5/68/b2f0cef8ed9d1ee49f0fe03777413007969d123cd6523afca4a4bfcdcf0d/mafan-0.2
.10.tar.gz (69kB)
    100% |████████████████████████████████| 71kB 2.9MB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "C:\Users\10020252\AppData\Local\Temp\pip-build-nzk8boks\mafan\setup.py", line 37, in <module>
        long_description=open('docs/README.md').read(), ##█内有中文”麻烦“，导致出错。Chinese "麻烦" included in the file, which caused the failure.
    UnicodeDecodeError: 'gbk' codec can't decode byte 0xa6 in position 1303: illegal multibyte sequence

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in C:\Users\10020252\AppData\Local\Temp\pip-build-nzk8boks\mafan\

**Comment by hermanschaaf** [comment] 2016-11-10 08:19
Hi @yinzuojie, I just pushed version 0.3.1 to Pypi, which might fix this error (though I am unable to reproduce it on Ubuntu). Can you try again?

**Comment by hermanschaaf** [comment] 2016-11-15 04:33
I'm going to go ahead and assume this is fixed now, feel free to re-open if that is not the case.

**Closed by hermanschaaf** 2016-11-15 04:33 UTC

**Comment by yinzuojie** [comment] 2016-12-09 14:47
that worked! sorry for long time no response ;）
